### ISSUE TITLE
激活过程

### ISSUE THREAD

**Issue by caffebeans** [ComeMorning/Modules-Learn#10]
请问一下，激活成功后，打开还是free.  是因为网络问题吗。 我是在内网环境下测试的。   激活必须要互联网吗

**Comment by wanZzz6** [comment]
是的，v9.2.1 版本以后激活后也得联网才能用，没有网络情况下得用 v9.2.1或者更早的版本，功能上也差别不大。如果要想在内网用最新版本，你得抓包分析服务器认证过程，然后自己搭一个认证服务，我没有这种使用场景，所以我懒得搞😂

**Comment by caffebeans** [comment]
我传进去一个9.2.1有版本，但是好像需要登陆，还是要网络，  是因为没有激活的原因吗

**Comment by caffebeans** [comment]
怎么能跳过登陆呢，因为是内网，没有外部网络

**Comment by wanZzz6** [comment]
首先你在内网机器上安装完成v9.2.1版本，不用登录激活， 然后找一台有网络的电脑上（系统不限）按照我的教程激活gitkraken，找到当前用户目录下的 `.gitkraken/` 文件夹，里面保存了已经激活账号的信息，将这个文件夹完整拷贝到你的内网机器上，并覆盖原来的 `.gitkraken/` 文件夹，就能达到激活的目的。

`.gitkraken/`目录位置：
- Windows
  - `C:\Users\{用户名}\AppData\Roaming\\.gitkraken` 
- Mac、Linux：
  -  `~/.gitkraken`

**Comment by caffebeans** [comment]
优秀

**Comment by wanderww** [comment]
啥软件啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月8日(星期一) 中午12:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [wanZzz6/Modules-Learn] 激活过程 (Issue #10)





 
优秀
 
&mdash;

**Comment by caffebeans** [comment]
我在内网安装了9.2 外网也安装了，将外网激活的.gitkraker复制到内网，  还是要登陆 快搞奔溃了😭😭😭😭

**Comment by caffebeans** [comment]
急需大佬帮忙

**Comment by wanZzz6** [comment]
![image](https://github.com/wanZzz6/Modules-Learn/assets/28629837/ec9c6ee0-3147-4653-a653-59e0e33b8db7)
我的电脑上没问题啊，你再重新来一遍。
先把联网机器上的Gitkraken完全卸载，并删除 `.gitkraken`  目录，重新安装 9.2.1 版本并激活；把内网机器上的 `.gitkraken` 目录也删除，从联网机器上重新拷贝过来，确保路径无误，且有读写权限

**Comment by wanderww** [comment]
这是啥软件来着？谁告诉我下，太长时间我忘了

**Comment by caffebeans** [comment]
gitkraken
