### ISSUE TITLE
Mac OS下，运行yarn gitcracken patcher时，报Error: EPERM: operation not permitted, copyfile '/Applications/GitKraken.app/Contents/Resources/app.asar' -> '/Applications/GitKraken.app/Contents/Resources/app.asar.1707134740021.backup'错误

### ISSUE THREAD

**Issue by andrewstang1985** [ComeMorning/Modules-Learn#11]
如题

**Comment by wanZzz6** [comment]
用系统自带的 Terminal 终端

**Comment by andrewstang1985** [comment]
> 用系统自带的 Terminal 终端
就是用系统自带的Terminal终端

**Comment by wanZzz6** [comment]
[Mac上加了sudo仍然提示权限不足](https://github.com/wanZzz6/Modules-Learn/blob/master/%E6%8A%80%E6%9C%AF/Gitkraken%20%E6%9C%80%E6%96%B0%E7%89%88v9.x%E7%A0%B4%E8%A7%A3%E6%95%99%E7%A8%8B.md#2-mac%E4%B8%8A%E5%8A%A0%E4%BA%86sudo%E4%BB%8D%E7%84%B6%E6%8F%90%E7%A4%BA%E6%9D%83%E9%99%90%E4%B8%8D%E8%B6%B3)

**Comment by andrewstang1985** [comment]
> [Mac上加了sudo仍然提示权限不足](https://github.com/wanZzz6/Modules-Learn/blob/master/%E6%8A%80%E6%9C%AF/Gitkraken%20%E6%9C%80%E6%96%B0%E7%89%88v9.x%E7%A0%B4%E8%A7%A3%E6%95%99%E7%A8%8B.md#2-mac%E4%B8%8A%E5%8A%A0%E4%BA%86sudo%E4%BB%8D%E7%84%B6%E6%8F%90%E7%A4%BA%E6%9D%83%E9%99%90%E4%B8%8D%E8%B6%B3)

已解决，多谢

**Comment by zhaojizhuang** [comment]
同遇到了问题，在` 设置-隐私与安全性中-App 管理中` 打开控制开关，再执行就成功了

![image](https://github.com/wanZzz6/Modules-Learn/assets/3124692/f8ec3ea4-9027-4391-ae15-c003cac2d408)
