### ISSUE TITLE
mac os 执行破解 yarn gitcracken patcher 报错

### ISSUE THREAD

**Issue by ZH0314** [ComeMorning/Modules-Learn#12]
(node:23961) UnhandledPromiseRejectionWarning: Error: Can't find app.asar!  at new Patcher
![1716515956848](https://github.com/wanZzz6/Modules-Learn/assets/43193952/fe12086d-f979-41da-b8cd-49842a54c2f8)

**Comment by wanZzz6** [comment]
[Ma上先安装到Application，再激活](https://github.com/wanZzz6/Modules-Learn/blob/master/%E6%8A%80%E6%9C%AF/Gitkraken%20%E6%9C%80%E6%96%B0%E7%89%88v9.x%E7%A0%B4%E8%A7%A3%E6%95%99%E7%A8%8B.md#21-macos%E7%94%A8%E6%88%B7)

**Comment by wanZzz6** [comment]
[Mac上先安装到Application，再激活](https://github.com/wanZzz6/Modules-Learn/blob/master/%E6%8A%80%E6%9C%AF/Gitkraken%20%E6%9C%80%E6%96%B0%E7%89%88v9.x%E7%A0%B4%E8%A7%A3%E6%95%99%E7%A8%8B.md#21-macos%E7%94%A8%E6%88%B7)

**Comment by ZH0314** [comment]
多谢大佬
