### ISSUE TITLE
Deepin系统 gitkraken 9.10.0 失败了

### ISSUE THREAD

**Issue by lingchenma** [ComeMorning/Modules-Learn#14]
![image](https://github.com/wanZzz6/Modules-Learn/assets/48959004/a275da0a-bf60-4162-8584-c7b1518cf69f)
linux 版本
最后一条修补，指令提示的错误
是不是需要降低版本呀？

**Comment by wanZzz6** [comment]
9.11.0 照样能激活，你这应该是Gitkraken没有正确安装，在默认安装路径下找不到app.asar文件

**Comment by lingchenma** [comment]
有办法指定路径吗？
![image](https://github.com/wanZzz6/Modules-Learn/assets/48959004/56237999-43a1-4692-80af-fcb5eca6b98b)
我是在这个路径下

**Comment by wanZzz6** [comment]
`gitcracken patcher --asar /opt/apps/com.gitkraken/files/resources/app.asar`

**Comment by lingchenma** [comment]
感谢了，成功了
