### ISSUE TITLE
改 host 之后还是会自动更新

### ISSUE THREAD

**Issue by eno-Zeng** [ComeMorning/Modules-Learn#15]
![hosts](https://github.com/user-attachments/assets/b5e87be6-2ade-479f-8e35-c616f3189277)

改了 host了，但是还是会自动更新，特别是电脑重启的时候，各位怎么破

**Comment by wanZzz6** [comment]
[已在hosts文件中添加了屏蔽更新条目，但还是会自动更新](https://github.com/wanZzz6/Modules-Learn/blob/master/%E6%8A%80%E6%9C%AF/Gitkraken%20%E6%9C%80%E6%96%B0%E7%89%88v9%E3%80%81v10%E7%A0%B4%E8%A7%A3%E6%95%99%E7%A8%8B.md#3-%E5%B7%B2%E5%9C%A8hosts%E6%96%87%E4%BB%B6%E4%B8%AD%E6%B7%BB%E5%8A%A0%E4%BA%86%E5%B1%8F%E8%94%BD%E6%9B%B4%E6%96%B0%E6%9D%A1%E7%9B%AE%E4%BD%86%E8%BF%98%E6%98%AF%E4%BC%9A%E8%87%AA%E5%8A%A8%E6%9B%B4%E6%96%B0)
