### ISSUE TITLE
7.5.1版本破解失败

### ISSUE THREAD

**Issue by WhatSpringIsThis** [ComeMorning/Modules-Learn#18]
运行yarn gitcracken patcher这一步报错Error: ENOENT: no such file or directory, open 'C:\Users\xxxx\AppData\Local\gitkraken\app-7.5.1\resources\app\src\main\static\main.bundle.js'

**Comment by wanZzz6** [comment]
![image](https://github.com/user-attachments/assets/9fa7f19a-d3dc-4c90-86c8-05ebada41575)
我这个不支持7.5，网上有很多旧版本的激活工具，你可以先找找，或者换到 8.2版本之后的

**Comment by WhatSpringIsThis** [comment]
好的，我去找找看
