### ISSUE TITLE
GitKraken 破解工具报错

### ISSUE THREAD

**Issue by 8824PPZ** [ComeMorning/Modules-Learn#2]
![image](https://user-images.githubusercontent.com/36729296/223301489-f5fe196e-2147-43c7-a4f3-893dea079588.png)

**Comment by JNUfeatherwit** [comment]
一样

**Comment by aAtrox007** [comment]
![image](https://user-images.githubusercontent.com/54255171/223701041-8618ca95-0ad1-4860-9f8c-f62028671e2e.png)
windows：所有历史残留都删除的情况下，下载完那个.exe程序，不打开，破解工具直接就解压，依次运行文档中的三条命令，到第三条就会报错。再次将历史残留都删除的情况下，打开.exe程序一次，关闭，依次运行文档中的三条命令，不报错。打开.exe程序登录github之后，未破解成功。麻烦大佬解决一下

**Comment by 284970854** [comment]
大佬,我的是这个问题.
![image](https://github.com/wanZzz6/Modules-Learn/assets/14988282/5caabac1-d688-429b-9709-864eafea3806)

**Comment by 284970854** [comment]
升级到官方最新版本,已解决.谢谢大佬的破解脚本

**Comment by wanZzz6** [comment]
> ![image](https://user-images.githubusercontent.com/36729296/223301489-f5fe196e-2147-43c7-a4f3-893dea079588.png)

你这个不是我给的破解工具吧？版本号怎么是 0.6.2？

**Comment by wanZzz6** [comment]
> 

破解之前必须先安装；不知道你用的Girkraken什么版本，换9.4.0以后的试试吧

**Comment by wanZzz6** [comment]
你破解工具在哪下的😂，太老了
