### ISSUE TITLE
我这里显示试用期是不是没有破解成功啊

### ISSUE THREAD

**Issue by danggerenba** [ComeMorning/Modules-Learn#3]
<img width="1245" alt="image" src="https://github.com/wanZzz6/Modules-Learn/assets/119066997/becbfb8b-8739-4b40-88aa-5560b5d1c469">

**Comment by danggerenba** [comment]
新手不太懂 但这里没有显示试用期
<img width="1246" alt="image" src="https://github.com/wanZzz6/Modules-Learn/assets/119066997/3552395d-b786-46d5-af73-2b8a9c0cd17a">

**Comment by wanZzz6** [comment]
你这是OK的，右下角显示橙色的 Pro 了
