### ISSUE TITLE
重启电脑后Gitkraken又从Pro变成Free

### ISSUE THREAD

**Issue by whcn** [ComeMorning/Modules-Learn#5]
#### 问题描述
按照教程步骤可以破解成功，但是一旦重启电脑，Gitkraken又会恢复Free版本。如果重新执行破解命令，就会提示已经打过补丁。只有重新安装gitkraken，并且把缓存删干净后才能再次破解成功，但是重启后又会出现同样的问题

#### 问题截图
![image](https://github.com/wanZzz6/Modules-Learn/assets/15919565/00e89c10-9fbd-4009-95a3-847da4c59687)

#### 版本信息
OS：macOS 13.4.1 (22F82)
Gitkraken：9.6.1

**Comment by wanZzz6** [comment]
软件最近更新了验证方式，把 api.gitkraken.com 禁用了会导致用户信息验证失败。
想要禁用自动更新在只需在hosts 文件中添加这一条即可:
`0.0.0.0 release.gitkraken.com `

**Comment by xlioncast** [comment]
破解成功以后，可以直击把执行程序拷贝到其他无网络的计算机上使用吗

**Comment by wanZzz6** [comment]
> 破解成功以后，可以直击把执行程序拷贝到其他无网络的计算机上使用吗

可以，得用 <=v9.2.1之前的旧版本， 参考：https://github.com/wanZzz6/Modules-Learn/issues/10#issuecomment-1880330132

**Comment by tailu123** [comment]
> 软件最近更新了验证方式，把 api.gitkraken.com 禁用了会导致用户信息验证失败。 想要禁用自动更新在只需在hosts 文件中添加这一条即可: `0.0.0.0 release.gitkraken.com `

hosts 文件在哪里，请问
