### ISSUE TITLE
Gitkraken 9.7.0 激活步骤执行成功，但是重新打开软件还是free版并提示登录。

### ISSUE THREAD

**Issue by zhangxiyu0819** [ComeMorning/Modules-Learn#6]
![image](https://github.com/wanZzz6/Modules-Learn/assets/35959984/73376297-8f2e-47b5-8e4d-c96f1d757d57)

**Comment by wanZzz6** [comment]
#4

**Comment by wanZzz6** [comment]
参考下： #4 和 #5
