### ISSUE TITLE
请问这个支持ubuntu吗？ubuntu 18.04 version.

### ISSUE THREAD

**Issue by mlion8** [ComeMorning/Modules-Learn#7]
![image](https://github.com/wanZzz6/Modules-Learn/assets/114807192/33578cf7-7e13-4fe9-9cdb-ab18e1e51f36)

yarn install, yarn build 都没问题，第三个command会报错。

**Comment by wanZzz6** [comment]
支持，你升级下nodejs版本试试

**Comment by wanZzz6** [comment]
我在WSL-Ubuntu 22.04 测了一下是没问题的
nodejs=v12.22.9
yarn=v1.22.19

![aaaa](https://github.com/wanZzz6/Modules-Learn/assets/28629837/2ca96d8a-ea1f-4084-afb7-5fc1775ae175)
