### ISSUE TITLE
mac 破解失败

### ISSUE THREAD

**Issue by JohnGuSir** [ComeMorning/Modules-Learn#8]
<img width="1389" alt="image" src="https://github.com/wanZzz6/Modules-Learn/assets/75824046/13c8be63-413c-4124-87f6-d697c9590ffc">

gitkraken 9.8.1
mac 13.5.2

**Comment by JohnGuSir** [comment]
@wanZzz6

**Comment by wanZzz6** [comment]
https://github.com/wanZzz6/Modules-Learn/blob/master/%E6%8A%80%E6%9C%AF/Gitkraken%20%E6%9C%80%E6%96%B0%E7%89%88v9.x%E7%A0%B4%E8%A7%A3%E6%95%99%E7%A8%8B.md#2-mac%E4%B8%8A%E5%8A%A0%E4%BA%86sudo%E4%BB%8D%E7%84%B6%E6%8F%90%E7%A4%BA%E6%9D%83%E9%99%90%E4%B8%8D%E8%B6%B3

**Comment by JohnGuSir** [comment]
thanks
