### ISSUE TITLE
第二步sudo yarn build有错误

### ISSUE THREAD

**Issue by lhw19670605** [ComeMorning/Modules-Learn#9]
<img width="907" alt="Screenshot 2023-10-05 at 9 13 00 PM" src="https://github.com/wanZzz6/Modules-Learn/assets/100477795/5080ccf1-26ec-434e-8231-204c85a23c06">

**Comment by wanZzz6** [comment]
你这个文件夹下是不是还有个Gitkraken目录？

**Comment by lhw19670605** [comment]
没有了，这是在GitkrakenCrack下面的GitCracken了

**Comment by lhw19670605** [comment]
<img width="615" alt="Screenshot 2023-10-05 at 10 15 08 PM" src="https://github.com/wanZzz6/Modules-Learn/assets/100477795/528acea0-c8d3-44f0-b7d3-3685a30107ef">
从新启动电脑后，再运行yarn build，出现的错误又不一样了

**Comment by wanZzz6** [comment]
用系统自带的Terminal 终端执行

**Comment by lhw19670605** [comment]
<img width="445" alt="Screenshot 2023-10-05 at 10 28 38 PM" src="https://github.com/wanZzz6/Modules-Learn/assets/100477795/a15f4c59-d008-4f7c-998b-38a3eea804e7">
用的是自带的Terminal，可能第一步就不对：No license field

**Comment by wanZzz6** [comment]
前两步不用加 sudo

**Comment by lhw19670605** [comment]
<img width="592" alt="Screenshot 2023-10-05 at 10 44 32 PM" src="https://github.com/wanZzz6/Modules-Learn/assets/100477795/13caf6da-06e5-4645-9e08-de0ebe2df9f1">
也试过不加，好像也不行，从执行yarn命令就提示No license field

**Comment by lhw19670605** [comment]
更新了一下typescript就成功了，谢谢！

**Comment by wanZzz6** [comment]
😥

**Comment by isamoye** [comment]
> typescript

更新到哪个版本呐
